import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Container } from "@/components/ui/container/Container";
import Navbar from "@/components/ui/navbar/Navbar";
// import { Navbar } from "@/components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "POC Contentful with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
